---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine

inputs:
  - name: pcfdemoapp
  - name: version

caches:
  - path: pcfdemoapp/m2

outputs:
  - name: build

run:
  path: pcfdemoapp/ci/tasks/build.sh
  args: [
    --input-dir, pcfdemoapp,
    --output-dir, build,
    --version-file, version/number,
    --artifactId, demo,
    --packaging, jar
  ]
