---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: pcfdemoapp
  - name: final-release
  - name: version

outputs:
  - name: makemanifest

run:
  path: pcfdemoapp/ci/tasks/make-manifest.sh
  args: [
    --input-dir, final-release,
    --output-dir, makemanifest,
    --input-manifest, pcfdemoapp/manifest-production.yml,
    --artifactId, demo,
    --packaging, jar,
    --version-file, version/number
  ]
