---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: pcfdemoapp
  - name: version

outputs:
  - name: prepare-final

run:
  path: pcfdemoapp/ci/tasks/prepare-final.sh
  args: [
    --output-dir, makemanifest,
    --version-file, version/number,
    --input-manifest, pcfdemoapp/manifest-production.yml,
    --artifactId, demo,
    --packaging, jar
  ]
