github-uri: https://github.com/tkaburagi1214/pcfdemoapp.git  # Change this to your fork
github-branch: master
gcs-bucket-release-candidates: pcfdemoapp-release-candidates
gcs-bucket-releases: pcfdemoapp-releases
gcs-bucket-version: pcfdemoapp
cf-api: "https://api.system.kabdev.xyz"  # Change the following to match your Cloud Foundry environment
cf-org: "pcfdemoapp"
cf-username: "kabu"
cf-password: "kabu"
cf-space-staging: "staging"
cf-space-prod: "production"
cf-manifest-host: pcfdemo-ci
#cf-manifest-host: pcfdemo-ci